USE [master]
GO

/****** Object:  Database [MES]    Script Date: 2023/5/8 10:01:26 ******/
CREATE DATABASE [MES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL\MSSQL\DATA\MES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL\MSSQL\DATA\MES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MES] SET ARITHABORT OFF 
GO

ALTER DATABASE [MES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MES] SET  MULTI_USER 
GO

ALTER DATABASE [MES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MES] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MES] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MES] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MES] SET  READ_WRITE 
GO


